import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit official Pikchr Site:
https://pikchr.org
The github repository of this wrapper plugin:
https://github.com/notlibrary/obsidian-adamantine-pick
*/
`;

const prod = (process.argv[2] === 'production');

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		...builtins],
	format: 'cjs',
	watch: !prod,
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	minify: prod ? true : false,
	treeShaking: true,
	outfile: 'main.js',
}).catch(() => process.exit(1));
