name: Bump Version
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Type of version (`major`, `minor`, `patch`)'
        required: true
        default: 'patch'
jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v7
      with:
        persist-credentials: false
        fetch-depth: 0
        token: ${{ secrets.PAT2 }}

    # Bump the version number
    - name: Update Version
      uses: MCKanpolat/auto-semver-action@v3
      id: version
      with:
        releaseType: ${{ github.event.inputs.type }}
        github_token: ${{ secrets.PAT2 }}

    # update the manifest.json with the new version
    - name: Update manifest version
      uses: jossef/action-set-json-field@v2.1
      with:
        file: manifest.json
        field: version
        value: ${{ steps.version.outputs.version }}

    # Commit the manifest.json and update the tag
    - name: Commit manifest
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git branch --show-current
        git add -u
        git commit -m "${{ steps.version.outputs.version }}"
        git tag -fa ${{ steps.version.outputs.version }} -m "${{ steps.version.outputs.version }}"

    # push the commit
    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.PAT2 }}
        tags: true
        branch: ${{ github.ref }}
